version: "2.4"
services:

  mysqldb-container:
    image: mysql/mysql-server
    container_name: mysqldb-container
    #    volumes:
    #      - mysql-data:/var/lib/mysql
    networks:
      - my_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=MovieBookingSystem
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  backend:
    image: tandon11/movieticketbackend
    container_name: backend
    networks:
      - my_net
    ports:
      - "8090:8090"
    links:
      - mysqldb-container
    depends_on:
      mysqldb-container:
        condition: service_healthy

  frontend:
    image: tandon11/movieticketfrontend
    container_name: frontend
    networks:
      - my_net
    ports:
      - "4200:4200"
    depends_on:
      - backend

#volumes:
#  mysql-data:

networks:
  my_net:
