version: "2.4"
services:
  clientnode:
    image: tandon11/movieticketfrontend:latest
    ports:
      - "4200:4200"
    networks:
      - my_net
  servernode:
    image: tandon11/movieticketbackend:latest
    ports:
      - "8090:8090"
    depends_on:
      - "dbnode"
    environment:
      MYSQL_HOST: "dbnode"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_PORT: "3306"
    networks: 
      - my_net
  dbnode:
    image: mysql 
    ports:
     - "3306:3306"
    volumes: 
      - /home/tandon_g/Documents/DockerCompose/dbnode:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "MovieBookingSystem"
      MYSQL_PASSWORD: "password"
    networks:
      - my_net

networks:
  my_net:

    
